<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Cdh on rmoff&#39;s random ramblings</title>
    <link>https://rmoff.github.io/categories/cdh/</link>
    <description>Recent content in Cdh on rmoff&#39;s random ramblings</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Tue, 05 Jul 2016 13:27:06 +0000</lastBuildDate>
    
	<atom:link href="https://rmoff.github.io/categories/cdh/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>Reset Hue password</title>
      <link>https://rmoff.github.io/2016/07/05/reset-hue-password/</link>
      <pubDate>Tue, 05 Jul 2016 13:27:06 +0000</pubDate>
      
      <guid>https://rmoff.github.io/2016/07/05/reset-hue-password/</guid>
      <description>(Ref)
The bit that caught me out was this kept failing with
Error: Password not present  and a Python stack trace that ended with
subprocess.CalledProcessError: Command &#39;/var/run/cloudera-scm-agent/process/78-hue-HUE_SERVER/altscript.sh sec-1-secret_key&#39; returned non-zero exit status 1  The answer (it seems) is to ensure that HUE_SECRET_KEY is set (to any value!)
Launch shell:
export HUE_SECRET_KEY=foobar /opt/cloudera/parcels/CDH-5.7.1-1.cdh5.7.1.p0.11/lib/hue/build/env/bin/hue shell  Reset password for hue, activate account and make it superuser
from django.contrib.auth.models import User user = User.</description>
    </item>
    
    <item>
      <title>Erroneous SwapFree on LXC causes problems with CDH install</title>
      <link>https://rmoff.github.io/2016/06/15/erroneous-swapfree-on-lxc-causes-problems-with-cdh-install/</link>
      <pubDate>Wed, 15 Jun 2016 17:52:00 +0000</pubDate>
      
      <guid>https://rmoff.github.io/2016/06/15/erroneous-swapfree-on-lxc-causes-problems-with-cdh-install/</guid>
      <description>Installing CDH 5.7 on Linux Containers (LXC) hosted on Proxmox 4. Everything was going well until Cluster Setup, and which point it failed on Start YARN (MR2 included)
Completed only 0/1 steps. First failure: Failed to execute command Start on service YARN (MR2 Included)  Log /var/log/hadoop-yarn/hadoop-cmf-yarn-NODEMANAGER-cdh57-01-node-02.moffatt.me.log.out showed:
org.apache.hadoop.service.AbstractService: Service containers-monitor failed in state INITED; cause: java.lang.NumberFormatException: For input string: &amp;quot;18446744073709550364&amp;quot; java.lang.NumberFormatException: For input string: &amp;quot;18446744073709550364&amp;quot;  Looking down the stack trace, this came from org.</description>
    </item>
    
  </channel>
</rss>